import type { BusinessNiche, SiteConfig } from "../types";

export type LegalDocKind = "privacy" | "terms" | "cancellation";

export type LegalSection = {
  title?: string;
  paragraphs: string[];
};

/**
 * Rutas públicas en español (aliases en inglés gestionados en App).
 */
export const LEGAL_ROUTES = {
  privacy: "/privacidad",
  terms: "/terminos",
  cancellation: "/cancelacion",
} as const;

/** Reemplaza marcadores estáticos por valores de `siteConfig`. */
export function interpolateLegalText(raw: string, site: SiteConfig): string {
  return raw
    .replaceAll("[NOMBRE_EMPRESA]", site.business.legalName)
    .replaceAll("[NOMBRE_COMERCIAL]", site.brand.name)
    .replaceAll("[DIRECCION]", site.business.address)
    .replaceAll("[TIEMPO_CANCELACION]", site.business.cancellationPolicy)
    .replaceAll("[EMAIL]", site.contact.email)
    .replaceAll("[TELEFONO]", site.contact.phone);
}

function interpolateSections(sections: LegalSection[], site: SiteConfig): LegalSection[] {
  return sections.map((s) => ({
    ...s,
    paragraphs: s.paragraphs.map((p) => interpolateLegalText(p, site)),
  }));
}

const NICHE_FALLBACK: BusinessNiche = "tattoo";

type Library = Record<BusinessNiche, Record<LegalDocKind, LegalSection[]>>;

const LIBRARY: Library = {
  tattoo: {
    privacy: [
      {
        paragraphs: [
          "The data controller responsible for processing your personal data is [NOMBRE_EMPRESA], with registered address at [DIRECCION]. For the purposes of this Policy, the trade name under which it operates publicly is [NOMBRE_COMERCIAL].",
          "This policy explains how we collect and process personal data submitted through our website, consultation forms, booking tools, and communications related to tattoo, piercing, and studio services.",
        ],
      },
      {
        title: "1. Data We May Collect",
        paragraphs: [
          "Identification and contact information such as full name, phone number, and email address.",
          "Booking and consultation details, including requested service, preferred artist, date, time, placement ideas, reference notes, and other information you voluntarily provide about your project.",
          "Operational records associated with your appointments, rescheduling requests, inquiries, and communications with the studio.",
          "Information relevant to the safe delivery of the service when voluntarily disclosed by you, such as allergies, skin sensitivities, medical considerations, or aftercare concerns.",
          "Minimal technical data generated by your visit to the site, such as IP address, browser type, and pages visited, where necessary for security and proper site operation.",
        ],
      },
      {
        title: "2. Purposes and Legal Basis",
        paragraphs: [
          "Managing consultation requests, bookings, confirmations, reschedules, waiting lists, and operational communications related to your appointment.",
          "Assessing project feasibility, artist availability, and the general suitability of a requested tattoo or piercing service before confirmation.",
          "Responding to inquiries submitted through forms, email, or studio communication channels.",
          "Maintaining records required for customer service, internal administration, legal compliance, and the defense of potential claims.",
          "Improving site security, preventing abusive or fraudulent use of booking tools, and ensuring the reliable operation of digital systems.",
        ],
      },
      {
        title: "3. Retention",
        paragraphs: [
          "We retain personal data only for as long as necessary to fulfill the purposes described above and to comply with applicable legal, accounting, health and safety, or record-keeping obligations. Certain appointment or consent-related records may be retained for longer where reasonably necessary to document the service provided or defend against claims.",
        ],
      },
      {
        title: "4. Recipients and Processors",
        paragraphs: [
          "We may use providers for web hosting, email delivery, payments (if enabled), booking infrastructure, analytics, and similar operational services. Where such providers process personal data on our behalf, we require them to act under appropriate contractual safeguards.",
          "We do not sell personal data or disclose client information to third parties for their own independent marketing purposes.",
        ],
      },
      {
        title: "5. Your Rights",
        paragraphs: [
          "Subject to applicable law, you may request access, rectification, erasure, restriction of processing, portability, or objection by contacting [EMAIL] and providing reasonable proof of identity. You may also lodge a complaint with the competent supervisory authority if you believe your rights have been infringed.",
        ],
      },
    ],
    terms: [
      {
        paragraphs: [
          "These Terms govern access to and use of the website operated by [NOMBRE_EMPRESA] ([NOMBRE_COMERCIAL]) and the request, consultation, and booking of tattoo, piercing, and related studio services.",
        ],
      },
      {
        title: "1. Use of the Site",
        paragraphs: [
          "Users agree to use the site lawfully, in good faith, and without interfering with its availability or security. Fraudulent bookings, misuse of communication forms, malicious software, or automated abuse of the booking system are strictly prohibited.",
        ],
      },
      {
        title: "2. Consultations and Bookings",
        paragraphs: [
          "Submitting a booking or consultation request does not guarantee acceptance of the requested service. Studio confirmation may depend on artist availability, design suitability, placement considerations, age requirements, health and safety criteria, or any other relevant professional assessment.",
          "Published prices, durations, and availability are indicative unless expressly stated otherwise. Final pricing may vary depending on size, complexity, placement, artist selection, number of sessions required, and any custom design work approved during consultation.",
        ],
      },
      {
        title: "3. Client Responsibilities",
        paragraphs: [
          "Clients must provide truthful and complete information relevant to the requested service, including any allergies, skin conditions, medical concerns, medications, or healing issues that could affect the session.",
          "Where required by law or studio policy, proof of age or identity may be requested before the service is provided. We reserve the right to refuse or postpone any service where legal, safety, hygiene, or professional standards are not met.",
        ],
      },
      {
        title: "4. Payments and Deposits",
        paragraphs: [
          "Where deposits or online payments are enabled, the terms of the applicable payment provider and the specific studio conditions communicated at the time of booking will apply. Deposits may be non-refundable in the circumstances stated in the applicable booking or cancellation policy.",
        ],
      },
      {
        title: "5. Limitation of Liability",
        paragraphs: [
          "To the maximum extent permitted by law, our liability arising from use of the website is limited to direct damages duly proven. We do not guarantee uninterrupted availability of digital services.",
          "Tattooing and piercing involve inherent variations related to skin type, healing, aftercare compliance, lifestyle, and other factors outside the studio's reasonable control. Clients are responsible for following aftercare instructions and for disclosing relevant information before the session.",
        ],
      },
    ],
    cancellation: [
      {
        paragraphs: [
          "[NOMBRE_COMERCIAL], operated by [NOMBRE_EMPRESA], maintains a cancellation and rescheduling policy designed to protect artist time, custom design preparation, and the integrity of scheduled studio sessions.",
        ],
      },
      {
        title: "1. Minimum Notice Period",
        paragraphs: [
          "To cancel or reschedule an appointment without late-cancellation consequences, clients must notify the studio at least: [TIEMPO_CANCELACION].",
          "This notice period is calculated from the scheduled start time of the confirmed session.",
        ],
      },
      {
        title: "2. Late Cancellations, Deposits, and No-Shows",
        paragraphs: [
          "Cancellations made outside the required notice window may result in loss of deposit, partial charges, or restrictions on future booking privileges, depending on the specific booking conditions communicated for the session.",
          "No-shows or repeated last-minute reschedules may require a non-refundable deposit or full prepayment before a new appointment is accepted.",
        ],
      },
      {
        title: "3. How to Cancel or Reschedule",
        paragraphs: [
          "Where available, appointments may be managed through the links included in the booking confirmation. You may also contact the studio by email at [EMAIL] or by phone at [TELEFONO], including your full name and the original date and time of the appointment.",
        ],
      },
      {
        title: "4. Studio-Initiated Changes",
        paragraphs: [
          "In exceptional circumstances, the studio may need to reschedule an appointment due to artist illness, safety concerns, technical issues, or other operational reasons. In such cases, we will use reasonable efforts to offer an alternative date or apply any deposit in accordance with the agreed booking conditions.",
        ],
      },
    ],
  },

  estetica: {
    privacy: [
      {
        paragraphs: [
          "El responsable del tratamiento es [NOMBRE_EMPRESA], domicilio en [DIRECCION]. Esta política complementa la información que el centro estético [NOMBRE_COMERCIAL] facilita sobre el tratamiento de datos personales obtenidos por la web y la agenda digital.",
        ],
      },
      {
        title: "1. Datos tratados",
        paragraphs: [
          "Identificación y contacto; datos de citas y tratamientos solicitados (sin incluir categorías especialmente protegidas salvo que usted los facilite voluntariamente en formularios).",
          "Información opcional sobre alergias o contraindicaciones cuando sea necesaria para la seguridad del tratamiento estético.",
          "Historial operativo de reservas y comunicaciones relacionadas con su visita.",
        ],
      },
      {
        title: "2. Finalidades",
        paragraphs: [
          "Organización de agenda, confirmaciones y recordatorios cuando proceda.",
          "Responder consultas previas y gestionar consentimientos informados cuando la actividad lo exija.",
          "Cumplimiento normativo y reclamaciones.",
          "Mejora del servicio y seguridad del canal digital.",
        ],
      },
      {
        title: "3. Conservación y comunicaciones",
        paragraphs: [
          "Los datos se conservarán durante los plazos necesarios para cada finalidad y obligación legal.",
          "Podremos comunicar datos a proveedores tecnológicos sujetos a contrato de tratamiento que participen en el funcionamiento del sitio o la agenda.",
        ],
      },
      {
        title: "4. Derechos",
        paragraphs: [
          "Puede ejercer los derechos reconocidos en la normativa aplicable escribiendo a [EMAIL], identificándose de forma razonable.",
        ],
      },
    ],
    terms: [
      {
        paragraphs: [
          "Al utilizar el sitio y reservar tratamientos en [NOMBRE_COMERCIAL] usted acepta estos Términos en nombre de [NOMBRE_EMPRESA].",
        ],
      },
      {
        title: "1. Servicios",
        paragraphs: [
          "Los tratamientos y duraciones publicadas son descriptivas; el profesional podrá adaptar la sesión según valoración previa y protocolos de seguridad.",
        ],
      },
      {
        title: "2. Reservas y contraindicaciones",
        paragraphs: [
          "El usuario declara informar de contraindicaciones médicas relevantes cuando el tipo de tratamiento lo requiera.",
          "La empresa podrá rechazar el servicio si existiera riesgo manifiesto para la salud del cliente o del personal.",
        ],
      },
      {
        title: "3. Productos y pagos",
        paragraphs: [
          "Los precios pueden actualizarse; el importe aplicable será el comunicado al confirmar la cita o en recepción según corresponda.",
        ],
      },
      {
        title: "4. Responsabilidad",
        paragraphs: [
          "La responsabilidad del centro frente al uso del sitio web se delimita conforme a la ley aplicable. Los resultados estéticos pueden variar según características individuales.",
        ],
      },
    ],
    cancellation: [
      {
        paragraphs: [
          "Política de cancelación y reprogramación de citas para servicios estéticos prestados por [NOMBRE_COMERCIAL] ([NOMBRE_EMPRESA]).",
        ],
      },
      {
        title: "1. Antelación mínima",
        paragraphs: [
          "Las cancelaciones o cambios de fecha/h deben solicitarse con al menos: [TIEMPO_CANCELACION] antes del inicio programado de la sesión.",
        ],
      },
      {
        title: "2. Efectos del incumplimiento",
        paragraphs: [
          "Las cancelaciones fuera de plazo y las ausencias pueden dar lugar a cargos parciales o políticas de depósito para futuras reservas, según lo comunicado en recepción o en la confirmación electrónica.",
        ],
      },
      {
        title: "3. Canales",
        paragraphs: [
          "Gestión online cuando esté disponible, o bien [TELEFONO] / [EMAIL] con los datos de la reserva.",
        ],
      },
    ],
  },

  abogado: {
    privacy: [
      {
        paragraphs: [
          "En cumplimiento del principio de transparencia, [NOMBRE_EMPRESA] (en adelante, el «Despacho»), con domicilio en [DIRECCION], informa sobre el tratamiento de datos personales obtenidos a través del presente sitio web y formularios de contacto del despacho [NOMBRE_COMERCIAL].",
        ],
      },
      {
        title: "1. Datos recabados",
        paragraphs: [
          "Identificación y datos de contacto profesionales que usted voluntariamente ingrese en formularios de consulta.",
          "Contenido de la consulta inicial (descripción genérica del asunto), sin que el mero envío del formulario establezca relación de asistencia jurídica sin contrato expreso.",
          "Datos técnicos básicos de conexión cuando resulten necesarios por seguridad.",
        ],
      },
      {
        title: "2. Finalidades",
        paragraphs: [
          "Valorar la viabilidad de una posible relación profesional y responder a solicitudes de información previa.",
          "Gestionar citas o videollamadas de primera entrevista cuando exista ese módulo.",
          "Cumplimiento de obligaciones legales aplicables al ejercicio de la profesión y prevención de blanqueo cuando corresponda conforme a normativa vigente.",
          "La base jurídica será la ejecución de medidas precontractuales, el consentimiento del interesado o el interés legítimo del Despacho en la gestión segura del canal, según cada tratamiento.",
        ],
      },
      {
        title: "3. Secreto profesional y destinatarios",
        paragraphs: [
          "Los datos se tratarán con confidencialidad conforme a las reglas del ejercicio de la abogacía. Solo tendrán acceso personal autorizado y encargados del tratamiento estrictamente necesarios (por ejemplo hosting o correo profesional), con las garantías contractuales adecuadas.",
        ],
      },
      {
        title: "4. Plazos y derechos",
        paragraphs: [
          "Los datos se conservarán durante el tiempo necesario para atender la consulta y, en su caso, la relación profesional y los plazos legales de conservación documental.",
          "Puede ejercer derechos de acceso, rectificación, supresión, limitación, portabilidad y oposición escribiendo a [EMAIL].",
        ],
      },
    ],
    terms: [
      {
        paragraphs: [
          "Los presentes Términos regulan el uso del sitio web de [NOMBRE_EMPRESA] y la información general publicada bajo la marca [NOMBRE_COMERCIAL]. No sustituyen el contrato de prestación de servicios jurídicos, que se formalizará por separado cuando proceda.",
        ],
      },
      {
        title: "1. Naturaleza informativa",
        paragraphs: [
          "Los contenidos del sitio tienen carácter general y no constituyen asesoramiento jurídico específico. Cada caso requiere análisis individualizado.",
        ],
      },
      {
        title: "2. Contacto y representación",
        paragraphs: [
          "El envío de formularios no crea por sí solo relación abogado-cliente hasta que el Despacho confirme por escrito la aceptación del encargo conforme a sus políticas internas y normativa aplicable.",
        ],
      },
      {
        title: "3. Honorarios",
        paragraphs: [
          "Las tarifas y modalidades de facturación serán las acordadas expresamente en propuesta o contrato de honorarios.",
        ],
      },
      {
        title: "4. Limitación de responsabilidad",
        paragraphs: [
          "Salvo disposición legal imperativa en contrario, el Despacho no será responsable de decisiones tomadas únicamente con base en información genérica del sitio sin contrato de asistencia.",
        ],
      },
    ],
    cancellation: [
      {
        paragraphs: [
          "Normas sobre cancelación o reprogramación de reuniones previas concertadas con [NOMBRE_COMERCIAL], titularidad de [NOMBRE_EMPRESA].",
        ],
      },
      {
        title: "1. Preaviso",
        paragraphs: [
          "Las cancelaciones o cambios de horario de reuniones agendadas deberán comunicarse con una antelación mínima de [TIEMPO_CANCELACION], salvo fuerza mayor debidamente acreditada.",
        ],
      },
      {
        title: "2. Consecuencias",
        paragraphs: [
          "El incumplimiento reiterado del preaviso podrá condicionar la aceptación de nuevas solicitudes de cita o el cobro de tiempo reservado, según lo acordado en cada caso.",
        ],
      },
      {
        title: "3. Comunicación",
        paragraphs: [
          "Las cancelaciones pueden notificarse a [EMAIL] o al teléfono [TELEFONO], identificando la fecha y hora originales de la reunión.",
        ],
      },
    ],
  },
};

function pickNiche(type: BusinessNiche): BusinessNiche {
  if (type in LIBRARY) return type;
  return NICHE_FALLBACK;
}

/** Secciones legales interpoladas listas para renderizar. */
export function getLegalDocument(kind: LegalDocKind, site: SiteConfig): LegalSection[] {
  const niche = pickNiche(site.business.type);
  const sections = LIBRARY[niche][kind];
  return interpolateSections(sections, site);
}
